site_name: ATOM Calibration Framework
site_url: https://lardemua.github.io/atom_documentation/
theme:
  name: readthedocs
  icon:
    admonition: <material/alert-circle
    repo: fontawesome/brands/git-alt
repo_url: https://github.com/lardemua/atom_documentation
repo_name: lardemua/atom_documentation
# edit_uri: "tree/main/docs/"
edit_uri: ""
markdown_extensions:
  - attr_list
  - toc
  - md_in_html
  - admonition
  - tables
nav:
  - "Introduction": "index.md"
  - "Getting Started": "getting_started.md"
  - "Calibration Procedures": "procedures.md"
  - "Calibration Examples": "examples.md"
  - "Evaluation Procedures": "evaluations.md"
  - "Multimedia": "multimedia.md"
  - "Acknowledgment": "acknowledgment.md"
